//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AnswerId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CreationDate { get; set; }
        public string Content { get; set; }
        public Nullable<int> AStatus { get; set; }
        public Nullable<int> voteCount { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
