//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteId { get; set; }
        public Nullable<int> U_Id { get; set; }
        public Nullable<int> Upvote { get; set; }
        public Nullable<int> Downvote { get; set; }
        public Nullable<int> VoteStatus { get; set; }
        public Nullable<int> Q_Id { get; set; }
        public Nullable<int> A_Id { get; set; }
    }
}
